### ISSUE TITLE
rpmbuild fails: calamari.conf is not a directory

### ISSUE THREAD

**Issue by Madko** [ceph/calamari#238]
Hi,

I'm trying to build rpm on CentOS 7 following the instructions.

It seems there is a wrong install command somewher:

```
./build-rpm.sh
[lot of build logs]
target: install-conf
# wsgi conf for graphite constructed in postinst
# log dirs for Django apps
/usr/bin/install: target '/tmp/calamari-repo/rpmbuild/BUILDROOT/calamari-server-1.2.1-104_gec86085.el7.centos.x86_64/etc/calamari/calamari.conf' is not a directory
make: *** [install-conf] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.iXCaP2 (%install)
```

I don't find yet where.

**Comment by GregMeno** [comment]
@Madko Would you please tell me more about the environment in which you are running ./build-rpm.sh ?
I am trying to reproduce this now.

**Comment by Madko** [comment]
Just a fresh CentOS 7 up-to-date. Some RPM have been installed to meet the build requirements. I will check if I still have the  VM I used to try to build calamari.

**Comment by GregMeno** [comment]
@Madko I have successfully built a server package for centos6.4 using the vagrant setup. 
You can see which distros and versions that we support by looking in the vagrant directory.

Centos7 is not something we have tested.

Perhaps you could use the vagrant setup as a starting point?

I suggest that you bring this conversation to our mailing list. http://lists.ceph.com/pipermail/ceph-calamari-ceph.com/ I would be happy to provide further guidance there.

**Comment by begonia** [comment]
I got the same error when I run build-rpm.sh in centos 7.

```
# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.0.1406 (Core) 
Release:        7.0.1406
Codename:       Core
```

**Comment by dmick** [comment]
It's behaving as though /usr/bin/install doesn't understand -D, which on my system is documented as "create all leading components of DEST except the last, then copy SOURCE to DEST".  Is your /usr/bin/install different?

**Comment by begonia** [comment]
@dmick my /usr/bin/install -D is as same as yours.  
the error shows:
```
/usr/bin/install: target '/opt/rpmbuild/BUILDROOT/calamari-server-1.2.1-106_g1b9b5a7.el7.centos.x86_64/etc/calamari/calamari.conf' is not a directory
make: *** [install-conf] Error 1
```
*calamari.conf* is not a directory.

**Comment by dmick** [comment]
is that path present?  Is some path like it present?

**Comment by begonia** [comment]
em, there is not a file named calamari.conf in the path. 
here is my directory tree, maybe helps:
```
[root@ceph-1 BUILDROOT]# pwd
/opt/rpmbuild/BUILDROOT
[root@ceph-1 BUILDROOT]# tree
.
└── calamari-server-1.2.1-106_g1b9b5a7.el7.centos.x86_64
    ├── etc
    │   ├── calamari
    │   ├── graphite
    │   │   ├── carbon.conf
    │   │   └── storage-schemas.conf
    │   ├── salt
    │   │   └── master.d
    │   │       └── calamari.conf
    │   └── supervisor
    │       └── conf.d
    │           └── calamari.conf
    ├── opt
    │   └── calamari
    │       └── conf
    │           └── calamari.wsgi
    └── var
        ├── lib
        │   ├── calamari
        │   ├── cthulhu
        │   └── graphite
        │       ├── log
        │       │   └── webapp
        │       └── whisper
        └── log
            ├── calamari
            └── graphite

22 directories, 5 files
```

**Comment by dmick** [comment]
Of course there's not a file named calamari.conf in the path; the install command is what's trying to put it there.  The install command is complaining about a missing directory, so I was asking about the paths in the destination path, which is /opt/rpmbuild/BUILDROOT/calamari-server-1.2.1-106_g1b9b5a7.el7.centos.x86_64/etc/calamari/calamari.conf.  Tree seems to show they are all there (the rest of the tree doesn't matter to that failure, of course).  So I don't know what's going wrong.  I would probably try that install command at the shell prompt, and if it's still not clear, strace it to figure out exactly what it's trying to tell you.

**Comment by begonia** [comment]
ok, I find the reason of this error happen.
as you see, the directory tree shows they are all there except etc/calamari/calamari.conf, so I read the code of Makefile, line 136 -167:
```bash
install-conf: $(CONFFILES)
	@echo "target: $@"
	@$(INSTALL) -D -m 0644 conf/calamari.wsgi \
		$(DESTDIR)/opt/calamari/conf/calamari.wsgi
	@$(INSTALL) -d $(DESTDIR)/etc/supervisor/conf.d
	@$(INSTALL) -D -m 0644 conf/supervisord.production.conf \
		$(DESTDIR)/etc/supervisor/conf.d/calamari.conf
	@$(INSTALL) -d $(DESTDIR)/etc/salt/master.d
	@$(INSTALL) -D -m 0644 conf/salt.master.conf \
		$(DESTDIR)/etc/salt/master.d/calamari.conf
	@$(INSTALL) -d $(DESTDIR)/etc/graphite
	@$(INSTALL) -D -m 0644 conf/carbon/carbon.conf \
		$(DESTDIR)/etc/graphite/carbon.conf
	@$(INSTALL) -D -m 0644 conf/carbon/storage-schemas.conf \
		$(DESTDIR)/etc/graphite/storage-schemas.conf
	# wsgi conf for graphite constructed in postinst
	# log dirs for Django apps
	@$(INSTALL) -d $(DESTDIR)/var/log/graphite
	@$(INSTALL) -d $(DESTDIR)/var/log/calamari
	@$(INSTALL) -d $(DESTDIR)/var/lib/graphite/log/webapp
	@$(INSTALL) -d $(DESTDIR)/var/lib/graphite/whisper
	@$(INSTALL) -d $(DESTDIR)/var/lib/calamari
	@$(INSTALL) -d $(DESTDIR)/var/lib/cthulhu

	@$(INSTALL) -d $(DESTDIR)/etc/calamari
	@$(INSTALL) -D -m 0644 conf/calamari/$(FLAVOR)/calamari.conf \
		$(DESTDIR)/etc/calamari/calamari.conf
	@$(INSTALL) -D -m 0644 conf/alembic.ini \
		$(DESTDIR)/etc/calamari/alembic.ini
	@$(INSTALL) -d $(DESTDIR)/etc/logrotate.d
	@$(INSTALL) -D -m 0644 conf/logrotate.d/calamari \
	    $(DESTDIR)/etc/logrotate.d/calamari
```
the difference is line 161 $(FLAVOR), and FLAVOR ?= $(shell ./get-flavor.sh)
and this is get-flavor.sh
```bash
#!/bin/bash

ID=$(lsb_release -i -s)
if [ $? != 0 ] ; then echo "$0: lsb_release failed..."; exit 1; fi
VERSION=$(lsb_release -r -s)

# ID is:
# Centos6.4: CentOS
# RHEL6: RedHatEnterpriseServer
# precise, trusty: Ubuntu
# wheezy: Debian
# SLES: SUSE Linux
# openSUSE: openSUSE project


case $ID in
    "CentOS"|"RedHatEnterpriseServer")
        case $VERSION in
            "7.0") ret="rhel7" ;;
            "6.5"|"6.4"|"6.3") ret="el6" ;;
            *) echo "$0: unhandled EL version $VERSION"; exit 1 ;;
        esac ;;
    "Ubuntu"|"Debian") ret="debian" ;;
    *SUSE*) ret="suse" ;;
    *) echo "$0: unhandled id $ID"; exit 1 ;;
esac

echo $ret
exit 0
```

in my environment,
```
[root@ceph-1 calamari]# lsb_release -r -s     
7.0.1406
```
as you know, it will exit 1 and raise this error.

so I changed line 19 to: 
```
 "7.0"|"7.0.1406") ret="rhel7" ;; 
```
luckly, build-rpm.sh runs successfully. thanks:)
