### ISSUE TITLE
RFE: Custom cluster name templated in DiskSpaceTargets.ejs?

### ISSUE THREAD

**Issue by aalba6675** [ceph/calamari#242]
This file is currently hardcoding the cluster name in 

servers.<%- hostname %>.diskspace._var_lib_ceph_osd_ceph-<%- id %>.<%- metric %>

Is it possible to template the cluster name as well? E.g.,

servers.<%- hostname %>.diskspace._var_lib_ceph_osd_<%- cluster %>-<%- id %>.<%- metric %>

Graphite graphs for diskspace are empty for a custom cluster name "myname"; diamond is sending
_var_lib_ceph_osd_myname- * (the mount point), but graphite is only rendering if myname == ceph.

**Comment by aalba6675** [comment]
Yep, sure:

http://tracker.ceph.com/issues/10456

**Comment by dmick** [comment]
Thanks!
