### ISSUE TITLE
Cannot Find Ceph Cluster

### ISSUE THREAD

**Issue by ghxandsky** [ceph/calamari#276]
I have install a ceph cluster of 4 nodes {mon,osd} on CentOS 7.1, Ceph 0.80.9. And I install Calamari on CentOS 7.1 , add mon on it , use ceph-deploy give admin to it, running "ceph -s" is ok. But Calamari UI tells me that "4 Ceph servers are connected to Calamari, but no Ceph cluster has been created yet. Please use ceph-deploy to create a cluster; please see the Inktank Ceph Enterprise documentation for more details.". How can I solve this problem ? Thanks :).

**Comment by GregMeno** [comment]
Would you please come to the mailing list for faster service?  
http://lists.ceph.com/listinfo.cgi/ceph-calamari-ceph.com
to get started debugging try running 'sudo salt '*' ceph.get_heartbeats' from the calamari node. Share the output and I would be happy to help you get it fixed.

**Comment by GregMeno** [comment]
@ghxandsky Did you get the help that you needed?

**Comment by tanght** [comment]
I runing 'sudo salt '*' ceph.get_heartbeats'
co_ceph_2:
    |_
      ----------
      boot_time:
          1436204176
      ceph_version:
          None
      services:
          ----------
          ceph-mds.1:
              ----------
              cluster:
                  ceph
              fsid:
                  41b56d5a-228f-4812-9ae6-b878c0ac7373
              id:
                  1
              status:
                  None
              type:
                  mds
              version:
                  0.84
    |_
      ----------
co_ceph_3:
    |_
      ----------
      boot_time:
          1436204177
      ceph_version:
          None
      services:
          ----------
          ceph-mon.co_ceph_3:
              ----------
              cluster:
                  ceph
              fsid:
                  41b56d5a-228f-4812-9ae6-b878c0ac7373
              id:
                  co_ceph_3
              status:
                  ----------
                  election_epoch:
                      10
                  extra_probe_peers:
                  monmap:
                      ----------
                      created:
                          2015-07-03 01:42:15.358720
                      epoch:
                          3
                      fsid:
                          41b56d5a-228f-4812-9ae6-b878c0ac7373
                      modified:
                          2015-07-06 23:50:48.468006
                      mons:
                          |_
                            ----------
                            addr:
                                192.168.2.162:6789/0
                            name:
                                co_ceph_1
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                192.168.2.163:6789/0
                            name:
                                co_ceph_2
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                192.168.2.164:6789/0
                            name:
                                co_ceph_3
                            rank:
                                2
                  name:
                      co_ceph_3
                  outside_quorum:
                  quorum:
                      - 0
                      - 2
                  rank:
                      2
                  state:
                      peon
                  sync_provider:
              type:
                  mon
              version:
                  0.84
    |_
      ----------
co_ceph_1:
    |_
      ----------
      boot_time:
          1436204173
      ceph_version:
          None
      services:
          ----------
          ceph-mds.0:
              ----------
              cluster:
                  ceph
              fsid:
                  41b56d5a-228f-4812-9ae6-b878c0ac7373
              id:
                  0
              status:
                  None
              type:
                  mds
              version:
                  0.84
          ceph-mon.co_ceph_1:
              ----------
              cluster:
                  ceph
              fsid:
                  41b56d5a-228f-4812-9ae6-b878c0ac7373
              id:
                  co_ceph_1
              status:
                  ----------
                  election_epoch:
                      10
                  extra_probe_peers:
                  monmap:
                      ----------
                      created:
                          2015-07-03 01:42:15.358720
                      epoch:
                          3
                      fsid:
                          41b56d5a-228f-4812-9ae6-b878c0ac7373
                      modified:
                          2015-07-06 23:50:48.468006
                      mons:
                          |_
                            ----------
                            addr:
                                192.168.2.162:6789/0
                            name:
                                co_ceph_1
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                192.168.2.163:6789/0
                            name:
                                co_ceph_2
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                192.168.2.164:6789/0
                            name:
                                co_ceph_3
                            rank:
                                2
                  name:
                      co_ceph_1
                  outside_quorum:
                  quorum:
                      - 0
                      - 2
                  rank:
                      0
                  state:
                      leader
                  sync_provider:
              type:
                  mon
              version:
                  0.84
          ceph-osd.0:
              ----------
              cluster:
                  ceph
              fsid:
                  41b56d5a-228f-4812-9ae6-b878c0ac7373
              id:
                  0
              status:
                  None
              type:
                  osd
              version:
                  0.84
          ceph-osd.1:
              ----------
              cluster:
                  ceph
              fsid:
                  41b56d5a-228f-4812-9ae6-b878c0ac7373
              id:
                  1
              status:
                  None
              type:
                  osd
              version:
                  0.84
    |_
      ----------


but in my GUI 
 3 Ceph servers are connected to Calamari, but no Ceph cluster has been created yet. Please use ceph-deploy to create a cluster; please see the Inktank Ceph Enterprise documentation for more details.

please help me.think you very much

**Comment by ksingh7** [comment]
@tanght we have another open issue #315 for this exactly same problem. Could you post and follow up there. This thread has already been closed.

Thanks , btw i am still waiting for the solution.
