### ISSUE TITLE
rhel7.box does not exist

### ISSUE THREAD

**Issue by ababurko** [ceph/calamari#293]
I'd like to build the calamari RPM's for RHEL7 and when I go to bring up the vm, vagrant cannot find the rhel7.box.

In calamari/vagrant/rhel7-build/Vagrantfile, the box_url is set to "file:/home/jenkins-build/rhel7.box" which does not exist in my env.

I tried building my own rhel7 box but it was one problem after another when running the salt command to build the RPM's.  If you can point me to a URL that I can download the rhel7.box from, I would greatly appreciate it.

thanks,
Bob

**Comment by dmick** [comment]
On 06/04/2015 05:49 PM, Bob Ababurko wrote:
> I'd like to build the calamari RPM's for RHEL7 and when I go to bring up
> the vm, vagrant cannot find the rhel7.box.
> 
> In calamari/vagrant/rhel7-build/Vagrantfile, the box_url is set to
> "file:/home/jenkins-build/rhel7.box" which does not exist in my env.

that's line 9.  See line 8, and lines 10-12?  That's your answer.
Line 9 is for building from the box we made here at redhat, which of
course has internal subscription managers, etc.

> I tried building my own rhel7 box but it was one problem after another
> when running the salt command to build the RPM's. If you can point me to
> a URL that I can download the rhel7.box from, I would greatly appreciate it.

Unfortunately it has to have an entitlement to install build dependencies.

Note that you need not necessarily do this in a Vagrant box; you can
also build without vagrant.

**Comment by GregMeno** [comment]
@ababurko I can offer some tips on building what stage of the salt is failing on your RHEL box?

**Comment by ksingh7** [comment]
@ababurko post logs to get help :+1:

**Comment by GregMeno** [comment]
@ababurko Have you found a way to satisfy your build?

**Comment by ababurko** [comment]
I did end up building building calamari with a Centos7.0 box and the rhel7
vagrant file and got it to build w/o errors using this page:

https://ceph.com/category/calamari/

I also built the calamari-client with the directions(same link) for RHEL7
which I hope will work(should) on a Centos7 host.

If there is a way to build all rpms for centos el7 and not have to futz
with tarballs, I would like to understand this.  :)

**Comment by ksingh7** [comment]
@ababurko did you build calamari-client packages using RHEL7 Vagrantfile ?? So you did not used precise-build Vagrantfile ?

My understanding was to first use precise-build Vagrant to generate *.tar.gz file for calamari-client then use either centos / RHEL Vagrant to generate *.rpm using this *tar.gz file. Is this correct ??

**Comment by dmick** [comment]
Yeah, that's how it works today.
