### ISSUE TITLE
Setting salt.run_highstate = true by default in Vagrantfile ?

### ISSUE THREAD

**Issue by ksingh7** [ceph/calamari#294]
http://calamari.readthedocs.org/en/latest/development/building_packages.html#calamari-server

Documentation doesn't mention that , after running ```$ vagrant up``` we need to manually execute
 ```$ sudo salt-call state.highstate```

Manually running salt-call is not a problem, but it would be nicer if we update Vagrantfile with ```salt.run_highstate = true``` so it gets executed with ``vagrant up``

Your thoughts please ?

**Comment by joehandzik** [comment]
I'm a fan of this plan, the separate high state call threw me off the first time I tried building calamari...

Joe



On Jun 7, 2015, at 1:58 PM, karan singh <notifications@github.com<mailto:notifications@github.com>> wrote:


http://calamari.readthedocs.org/en/latest/development/building_packages.html#calamari-server

Documentation doesn't mention that , after running $ vagrant up we need to manually execute
$ sudo salt-call state.highstate

Manually running salt-call is not a problem, but it would be nicer if we update Vagrantfile with salt.run_highstate = true so it gets executed with vagrant up

Your thoughts please ?

�

**Comment by dmick** [comment]
It's intentional.

**Comment by jcsp** [comment]
For some reason there was a docs update on a branch but not master. @dmick @GregMeno you guys still using master for the latest code, right?

**Comment by jcsp** [comment]
(update was https://github.com/ceph/calamari/pull/284/files)

**Comment by GregMeno** [comment]
Yes we are still using master. I forgot to merge it up. I will to review the PRs and make sure master contains all the latest.

**Comment by ksingh7** [comment]
@jcsp @GregMeno @dmick Thanks for adding this to documentation :+1:
