### ISSUE TITLE
3 Ceph servers are connected to Calamari, but no Ceph cluster has been created yet

### ISSUE THREAD

**Issue by ksingh7** [ceph/calamari#315]
Hi i am facing this very annoying problem with calamari.

![image](https://cloud.githubusercontent.com/assets/9701902/8496584/03524182-217f-11e5-9f7a-fc7533ef1ab9.png)

I have tried 3 time with each time fresh start but it never worked. Its not only me facing this problem there are other community members facing the exact same problems since few weeks.

Output from my last attempt : http://lists.ceph.com/pipermail/ceph-calamari-ceph.com/2015-June/000169.html

**So far there is no concrete solution , really appreciate if someone who knows calamari from core , can pop up and help in troubleshooting.**

Output from this attempt : 

- 3 node ceph cluster ( Giant )
- CentOS7

```
[root@ceph-node1 calamari]# rpm -qa | egrep -i "calamari|salt|diamond|supervisor"
salt-master-2014.7.5-1.el7.centos.noarch
calamari-server-1.3.0.1-63_g11f74e4.el7.centos.x86_64
salt-2014.7.5-1.el7.centos.noarch
supervisor-3.0-1.el7.noarch
diamond-3.4.582-0.noarch
calamari-clients-1.2.2-32_g931ee58.el7.centos.x86_64
salt-minion-2014.7.5-1.el7.centos.noarch
[root@ceph-node1 calamari]#
```
```
[root@ceph-node1 calamari]# salt-key -L
Accepted Keys:
ceph-node1
ceph-node2
ceph-node3
Unaccepted Keys:
Rejected Keys:
[root@ceph-node1 calamari]#
```
```
[root@ceph-node1 calamari]# salt '*' test.ping
ceph-node3:
    True
ceph-node2:
    True
ceph-node1:
    True
[root@ceph-node1 calamari]#
```
```
[root@ceph-node1 calamari]# salt '*' ceph.get_heartbeats
ceph-node3:
    |_
      ----------
      boot_time:
          1435909024
      ceph_version:
          0.87.2-0.el7.centos
      services:
          ----------
          ceph-mon.ceph-node3:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  ceph-node3
              status:
                  ----------
                  election_epoch:
                      880
                  extra_probe_peers:
                  monmap:
                      ----------
                      created:
                          0.000000
                      epoch:
                          5
                      fsid:
                          9609b429-eee2-4e23-af31-28a24fcf5cbc
                      modified:
                          2015-07-02 21:15:01.654907
                      mons:
                          |_
                            ----------
                            addr:
                                192.168.1.101:6789/0
                            name:
                                ceph-node1
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                192.168.1.102:6789/0
                            name:
                                ceph-node2
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                192.168.1.103:6789/0
                            name:
                                ceph-node3
                            rank:
                                2
                  name:
                      ceph-node3
                  outside_quorum:
                  quorum:
                      - 1
                      - 2
                  rank:
                      2
                  state:
                      peon
                  sync_provider:
              type:
                  mon
              version:
                  0.87.2
          ceph-osd.6:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  6
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
          ceph-osd.7:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  7
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
          ceph-osd.8:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  8
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
    |_
      ----------
ceph-node2:
    |_
      ----------
      boot_time:
          1435908978
      ceph_version:
          0.87.2-0.el7.centos
      services:
          ----------
          ceph-mds.ceph-node2:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  ceph-node2
              status:
                  None
              type:
                  mds
              version:
                  0.87.2
          ceph-mon.ceph-node2:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  ceph-node2
              status:
                  ----------
                  election_epoch:
                      880
                  extra_probe_peers:
                  monmap:
                      ----------
                      created:
                          0.000000
                      epoch:
                          5
                      fsid:
                          9609b429-eee2-4e23-af31-28a24fcf5cbc
                      modified:
                          2015-07-02 21:15:01.654907
                      mons:
                          |_
                            ----------
                            addr:
                                192.168.1.101:6789/0
                            name:
                                ceph-node1
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                192.168.1.102:6789/0
                            name:
                                ceph-node2
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                192.168.1.103:6789/0
                            name:
                                ceph-node3
                            rank:
                                2
                  name:
                      ceph-node2
                  outside_quorum:
                  quorum:
                      - 1
                      - 2
                  rank:
                      1
                  state:
                      leader
                  sync_provider:
              type:
                  mon
              version:
                  0.87.2
          ceph-osd.3:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  3
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
          ceph-osd.4:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  4
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
          ceph-osd.5:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  5
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
    |_
      ----------
ceph-node1:
    |_
      ----------
      boot_time:
          1435908932
      ceph_version:
          0.87.2-0.el7.centos
      services:
          ----------
          ceph-mon.ceph-node1:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  ceph-node1
              status:
                  ----------
                  election_epoch:
                      0
                  extra_probe_peers:
                  monmap:
                      ----------
                      created:
                          0.000000
                      epoch:
                          2
                      fsid:
                          9609b429-eee2-4e23-af31-28a24fcf5cbc
                      modified:
                          2015-07-02 21:15:01.654907
                      mons:
                          |_
                            ----------
                            addr:
                                192.168.1.101:6789/0
                            name:
                                ceph-node1
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                192.168.1.102:6789/0
                            name:
                                ceph-node2
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                192.168.1.103:6789/0
                            name:
                                ceph-node3
                            rank:
                                2
                  name:
                      ceph-node1
                  outside_quorum:
                      - ceph-node1
                  quorum:
                  rank:
                      0
                  state:
                      probing
                  sync_provider:
              type:
                  mon
              version:
                  0.87.2
          ceph-osd.0:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  0
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
          ceph-osd.1:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  1
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
          ceph-osd.2:
              ----------
              cluster:
                  ceph
              fsid:
                  9609b429-eee2-4e23-af31-28a24fcf5cbc
              id:
                  2
              status:
                  None
              type:
                  osd
              version:
                  0.87.2
    |_
      ----------
[root@ceph-node1 calamari]#
```

Ceph cluster REST API ( http://192.168.1.101/api/v2/cluster )works

![image](https://cloud.githubusercontent.com/assets/9701902/8497265/7ceb8404-2184-11e5-9d07-04672bebefd4.png)

**Comment by tanght** [comment]
how can i rest  API ?

**Comment by tanght** [comment]
I met the same problem, can you tell me how to solve?

**Comment by tanght** [comment]
it will help you
https://webcache.googleusercontent.com/search?q=cache:http://wiki.ceph.com/Guides/How_To/Get_Started_with_the_Calamari_REST_API_and_PHP&gws_rd=cr
https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by tanght** [comment]
@ksingh7 
https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

**Comment by ksingh7** [comment]
@tanght Thanks , could you please explain a bit more on this new bootstrap-salt.sh ?

**Comment by ababurko** [comment]
I am facing the same issue with the calamari gui(client?) not seeing my cluster upon install.  As far as I can tell my salt installation is working.....output below.

My cluster is running hammerhead.  5 OSD nodes, 3 mon nodes, all running Centos7.0.

[bababurko@dcalamari01 ~]$ cat /etc/redhat-release
CentOS Linux release 7.0.1406 (Core)

[bababurko@dcalamari01 ~]$ rpm -qa | egrep -i "calamari|salt|diamond|supervisor"
supervisor-3.0-1.el7.noarch
salt-2014.7.5-1.el7.noarch
diamond-3.4.67-0.noarch
salt-master-2014.7.5-1.el7.noarch
calamari-server-1.3-rc_50_gd6e43c6.el7.centos.x86_64
salt-minion-2014.7.5-1.el7.noarch

[bababurko@dcalamari01 ~]$ sudo salt-key -L
Accepted Keys:
dcalamari01.tag-dev.com
dcephmon01.tag-dev.com
dcephmon02.tag-dev.com
dcephmon03.tag-dev.com
dcephosd01.tag-dev.com
dcephosd02.tag-dev.com
dcephosd03.tag-dev.com
dcephosd04.tag-dev.com
dcephosd05.tag-dev.com
Unaccepted Keys:
Rejected Keys:

[bababurko@dcalamari01 ~]$ sudo salt '*' test.ping
dcalamari01.tag-dev.com:
    True
dcephmon02.tag-dev.com:
    True
dcephmon01.tag-dev.com:
    True
dcephosd01.tag-dev.com:
    True
dcephosd05.tag-dev.com:
    True
dcephosd02.tag-dev.com:
    True
dcephosd03.tag-dev.com:
    True
dcephosd04.tag-dev.com:
    True
dcephmon03.tag-dev.com:
    True

[bababurko@dcalamari01 ~]$ sudo salt '*' ceph.get_heartbeats
dcalamari01.tag-dev.com:
    |_
      ----------
      boot_time:
          1435615381
      ceph_version:
          None
      services:
          ----------
    |_
      ----------
dcephosd02.tag-dev.com:
    |_
      ----------
      boot_time:
          1434597013
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-osd.10:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  10
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.11:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  11
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.6:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  6
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.7:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  7
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.8:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  8
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.9:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  9
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
    |_
      ----------
dcephosd05.tag-dev.com:
    |_
      ----------
      boot_time:
          1434574418
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-osd.24:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  24
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.25:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  25
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.26:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  26
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.27:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  27
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.28:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  28
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.29:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  29
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
    |_
      ----------
dcephosd01.tag-dev.com:
    |_
      ----------
      boot_time:
          1434592399
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-osd.0:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  0
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.1:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  1
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.2:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  2
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.3:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  3
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.4:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  4
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.5:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  5
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
    |_
      ----------
dcephosd03.tag-dev.com:
    |_
      ----------
      boot_time:
          1434574398
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-osd.12:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  12
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.13:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  13
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.14:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  14
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.15:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  15
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.16:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  16
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.17:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  17
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
    |_
      ----------
dcephosd04.tag-dev.com:
    |_
      ----------
      boot_time:
          1434592613
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-osd.18:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  18
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.19:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  19
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.20:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  20
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.21:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  21
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.22:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  22
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
          ceph-osd.23:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  23
              status:
                  None
              type:
                  osd
              version:
                  0.94.1
    |_
      ----------
dcephmon01.tag-dev.com:
    |_
      ----------
      boot_time:
          1434573876
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-mon.dcephmon01:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  dcephmon01
              status:
                  ----------
                  election_epoch:
                      8
                  extra_probe_peers:
                      - 10.98.21.49:6789/0
                      - 10.98.21.117:6789/0
                  monmap:
                      ----------
                      created:
                          0.000000
                      epoch:
                          1
                      fsid:
                          80fbd571-c095-4ad8-9f1b-7feada6ca5c1
                      modified:
                          0.000000
                      mons:
                          |_
                            ----------
                            addr:
                                10.98.21.28:6789/0
                            name:
                                dcephmon01
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                10.98.21.49:6789/0
                            name:
                                dcephmon02
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                10.98.21.117:6789/0
                            name:
                                dcephmon03
                            rank:
                                2
                  name:
                      dcephmon01
                  outside_quorum:
                  quorum:
                      - 0
                      - 1
                      - 2
                  rank:
                      0
                  state:
                      leader
                  sync_provider:
              type:
                  mon
              version:
                  0.94.1
    |_
      ----------
dcephmon03.tag-dev.com:
    |_
      ----------
      boot_time:
          1434573927
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-mon.dcephmon03:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  dcephmon03
              status:
                  ----------
                  election_epoch:
                      8
                  extra_probe_peers:
                      - 10.98.21.28:6789/0
                      - 10.98.21.49:6789/0
                  monmap:
                      ----------
                      created:
                          0.000000
                      epoch:
                          1
                      fsid:
                          80fbd571-c095-4ad8-9f1b-7feada6ca5c1
                      modified:
                          0.000000
                      mons:
                          |_
                            ----------
                            addr:
                                10.98.21.28:6789/0
                            name:
                                dcephmon01
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                10.98.21.49:6789/0
                            name:
                                dcephmon02
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                10.98.21.117:6789/0
                            name:
                                dcephmon03
                            rank:
                                2
                  name:
                      dcephmon03
                  outside_quorum:
                  quorum:
                      - 0
                      - 1
                      - 2
                  rank:
                      2
                  state:
                      peon
                  sync_provider:
              type:
                  mon
              version:
                  0.94.1
    |_
      ----------
dcephmon02.tag-dev.com:
    |_
      ----------
      boot_time:
          1434573945
      ceph_version:
          0.94.1-0.el7.centos
      services:
          ----------
          ceph-mon.dcephmon02:
              ----------
              cluster:
                  ceph
              fsid:
                  80fbd571-c095-4ad8-9f1b-7feada6ca5c1
              id:
                  dcephmon02
              status:
                  ----------
                  election_epoch:
                      8
                  extra_probe_peers:
                      - 10.98.21.28:6789/0
                      - 10.98.21.117:6789/0
                  monmap:
                      ----------
                      created:
                          0.000000
                      epoch:
                          1
                      fsid:
                          80fbd571-c095-4ad8-9f1b-7feada6ca5c1
                      modified:
                          0.000000
                      mons:
                          |_
                            ----------
                            addr:
                                10.98.21.28:6789/0
                            name:
                                dcephmon01
                            rank:
                                0
                          |_
                            ----------
                            addr:
                                10.98.21.49:6789/0
                            name:
                                dcephmon02
                            rank:
                                1
                          |_
                            ----------
                            addr:
                                10.98.21.117:6789/0
                            name:
                                dcephmon03
                            rank:
                                2
                  name:
                      dcephmon02
                  outside_quorum:
                  quorum:
                      - 0
                      - 1
                      - 2
                  rank:
                      1
                  state:
                      peon
                  sync_provider:
              type:
                  mon
              version:
                  0.94.1
    |_
      ----------

**Comment by ababurko** [comment]
I have tried the above recommended bootstrap-salt.sh on all my nodes and am still facing the same no cluster created issue.  The script upgraded salt & salt-minion to 2015.5.2-3.el7 which I previously downgraded from earlier(to 2014.7.5-1.el7) as an approach to fix my "salt issue".  I say this tongue in cheek as it doesn't really look like I have a salt issue as all my salt commands seem to be working from my calamari server before and after the version changes.

Can help identify what part is not working?  All of minions are responding when salt commands are ran against them via cmd line.  I'm stuck.

**Comment by GregMeno** [comment]
http://tracker.ceph.com/issues/12264

**Comment by GregMeno** [comment]
Issue has migrated to the bug tracker.

**Comment by sejames** [comment]
I also had to downgrade to salt-2014.1.11-1 for entire cluster , 2014.7.5 worked better then 2015.8.5 but did not find the cluster on 2014.7.5. I did notice on installation of salt-2014.1.11-1 that both sshpass and python-libcloud were also installed. If your lucky you might find the salt rpms on some EPEL mirror yet to delete them = http://mirror.oasis.onnetcorp.com/epel/testing/7/x86_64/s/
