### ISSUE TITLE
Unit tests fail without DJANGO_SETTINGS_MODULE being defined

### ISSUE THREAD

**Issue by joehandzik** [ceph/calamari#317]
Pretty much immediately, most unit tests fail in the unit test directories (cthulhu/tests, rest-api/tests) if DJANGO_SETTINGS_MODULE is not set to something. I set it to a blank file and all the failures went away. Is there a cleaner way to set this up in the environment?

**Comment by GregMeno** [comment]
@joehandzik are you using make check?

**Comment by joehandzik** [comment]
No, I was just running make. If ''make check" would have caught/generated that, then we can close this.

On Aug 5, 2015, at 2:35 PM, Gregory Meno <notifications@github.com<mailto:notifications@github.com>> wrote:


@joehandzik<https://github.com/joehandzik> are you using make check?

�

**Comment by GregMeno** [comment]
Yes, make check or make unit_tests is the correct way to invoke the tests
