### ISSUE TITLE
Copyright additions?

### ISSUE THREAD

**Issue by joehandzik** [ceph/calamari#324]
Kind of a weird one.

There's a coyright section for Red Hat here: https://github.com/ceph/calamari/blob/c64121ab01aef0be6dfc3bef1940e21fe09af45f/COPYING

However...HP has requested that I add HP copyright to any files that I make significant additions to. Trouble is, unlike the Ceph project, Calamari doesn't have the standard chunk of space at the top of source files dedicated to things like:

(c) Copyright 2015 Hewlett-Packard Development Company, L.P.;

Any idea where it would be best to put that sort of thing?

**Comment by jcsp** [comment]
Without making any comment on legal issues, I can briefly note that in upstream ceph, there is no de-facto practice of adding attribution lines to file headers as more contributors participate.  Instead, the Signed-off-by line in your commit message serves the purpose of tracking who contributed what.  In that sense there *is* a formal record that your contributions came from an hp.com email address.

The notes on how this is handled in ceph are here: https://github.com/ceph/ceph/blob/master/SubmittingPatches -- I don't know that anyone has formally applied the same policy to this repository, but I can't see why it wouldn't be the same.

**Comment by joehandzik** [comment]
Sure, I agree with all that @jcsp. And I tried to make that argument with HP Legal, but didn't have many legs to stand on when I searched through the Ceph repo and found instances like this:

https://github.com/ceph/ceph/blob/efededa0107eebd4abc0e08dd34200d6ca175626/src/test/test-ceph-helpers.sh#L3

I can follow up with them to see if they're satisfied with that explanation for Calamari, but I plan to add HP copyright to the Ceph files that are beyond bugfixes and enhancements. Do you expect that I'll get pushback from a patch to do that in Ceph? Perhaps I should have gotten that in along with the patch itself, but I didn't want to disturb my patch with yet another commit (even if it was just editing comments).

**Comment by dmick** [comment]
That is one innovative bash script.

**Comment by joehandzik** [comment]
It's not the ONLY instance. :P The number of copyrights on that one are pretty funny though.

**Comment by joehandzik** [comment]
This is arguably a much better example: https://github.com/ceph/ceph/commit/d4d6ff0706ff1591ce8b87199bba0a88a980f424

**Comment by jcsp** [comment]
I can't really predict whether you'll get pushback, but if every contributor did it we would end up with large lists in headers, which would be completely redundant as we already have a much more specific record of contributions in the git history.

That said, I wouldn't be surprised if folks just didn't care all that much about boilerplate (@liewegas ?)

**Comment by joehandzik** [comment]
I'll submit a PR into Ceph and see how it goes. I still don't have a good feel for how any of this should be handled going forward in Calamari, but I can bring it up in the standup meeting today.

**Comment by GregMeno** [comment]
@joehandzik I'll contact our people and see if they have any specific guidance.
Otherwise I'm happy to have whatever we do in ceph be the practice here.

**Comment by liewegas** [comment]
I don't care about boilerplate.  Whatever greases legal's wheels (within reason) is okay with me.

**Comment by joehandzik** [comment]
Ok, this is clarified for me. @GregMeno and I will figure out the right way to go about all this in Calamari.
