### ISSUE TITLE
calamari_web should allow for DB port to be configured

### ISSUE THREAD

**Issue by wyllys66** [ceph/calamari#344]
When installing calamari-server on a system with a postgres db that already exists and which listens on an alternate port (5433 vs 5432, for example), initialization fails because the calamari_web settings does not check the PORT value when setting up the default values.

In calamari_web/settings.py , the DATABASES['default'] dictionary needs a "PORT" k/v entry such as:
```
config.get("calamari_web", "db_port") 
```
so the admin can configure it to use PG databases on alternate ports.

**Comment by GregMeno** [comment]
@wyllys66 Makes sense to me. Thank you.

**Comment by GregMeno** [comment]
merged #345
