### ISSUE TITLE
Incident of Calamari web.

### ISSUE THREAD

**Issue by Midori-ch** [ceph/calamari#348]
Hi,
In test environment only one monitor. When ceph daemon on monitor goes down that calamari web "host" section will display 0 MON. 
But after monitor's daemon come back, the web still display 0 MON. And this status will not recovery. 

ceph：0.94
calamari-server：1.3.0.1-11
calamari-client：1.3-rc-12

**Comment by GregMeno** [comment]
What is the status of that monitor?
Is this issue anything like http://tracker.ceph.com/issues/10496

**Comment by Midori-ch** [comment]
Hi GregMeno, 
Thanks for your help. Mon and cluster status are healthy. 
![image 1](https://cloud.githubusercontent.com/assets/11845196/9778196/f03194f2-579f-11e5-876b-ebdb52d91f6f.png)

**Comment by dmick** [comment]
@Midori-ch: I don't understand; are you no longer experiencing a problem?

**Comment by Midori-ch** [comment]
Hi Dmick
Sorry to make you feel confused. I tried to restart monitor daemon and salt-minion.
I hope section "Host" will display "1 Mon".

**Comment by dmick** [comment]
Oh, right.  I saw monitors 1/1 and didn't notice the blue box.  sorry.

**Comment by Midori-ch** [comment]
The mon show up after execute "calamari-ctl clear" and restart salt service.
Thank you for all your helps. Close this issue.
