### ISSUE TITLE
Documentation improvements

### ISSUE THREAD

**Issue by mbornoz** [ceph/calamari#364]
Hi,

Since manifestly the .deb packages are no longer available on http://download.ceph.com/calamari, it should be useful to replace this link (page [operations/server_install](http://calamari.readthedocs.org/en/latest//en/latest/operations/server_install.html)) by the [development/building_packages page](http://calamari.readthedocs.org/en/latest//en/latest/development/building_packages.html).

Two other things that could be improved:
 * the documentation is focused on precise, while most Ceph users are now on trusty, the best might be to write "Ubuntu LTS"
 * calamari-client was renamed, documentation must be modified accordingly

Thanks a lot,
Mathieu

**Comment by GregMeno** [comment]
@mbornoz Thank you for the feedback. Trusty packages have been restored to http://download.ceph.com/calamari

**Comment by theaverageguy** [comment]
I am on it. I would like to be a part of Ceph for this GSoC and I wish to express my interest with some bug fixing! :)
