### ISSUE TITLE
Question of graphite timezone.

### ISSUE THREAD

**Issue by Midori-ch** [ceph/calamari#369]
Hi, 
I want to change the timezone setting of graphite. But I can not find /opt/graphite/webapp/graphite/local_settings.py. How can I do that ？

**Comment by GregMeno** [comment]
@Midori-ch you could change the time-zone here /opt/calamari/venv/lib/python2.7/site-packages/calamari_web-0.1-py2.7.egg/calamari_web/settings.py

You'll need to restart the webserver for the change to take effect

**Comment by GregMeno** [comment]
@Midori-ch  did this help? Can I close this issue?

**Comment by Midori-ch** [comment]
Hi Greg,
It's works ! Pls close this issue. Thank you so much !
