### ISSUE TITLE
pip install --no-install carbon

### ISSUE THREAD

**Issue by zphj1987** [ceph/calamari#373]
/root/calamari/rpmbuild/BUILD/calamari-server-1.3.1.1/venv/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ ./bin/python ./bin/pip install --no-install carbon

Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --no-install
make: *** [build-venv-carbon] Error 1

i build calamari rpm on centos6 but dispaly this,pip install --no-install carbon ,but my pip does not has --no-install option

**Comment by GregMeno** [comment]
@zphj1987 looks like they changed pip install --no-install in 7.0 to be pip unpack
https://github.com/pypa/pip/issues/906

**Comment by zphj1987** [comment]
yes  i found it ，i run it on  oracle linux  has this problem ,but i changge to centos 6 , it has no problem ,so ,ithink ,it is the system problem ,maybe something diffrent in ol linux

**Comment by ktdreyer** [comment]
See #428
