### ISSUE TITLE
i want diable login auth,how to do it?

### ISSUE THREAD

**Issue by zphj1987** [ceph/calamari#375]
i had a calamari web  , and i want  open the web directly with out input username and passwd ,how can i do it ,thank you !

**Comment by GregMeno** [comment]
@zphj1987 Are you trying to disable auth from the API, from the dashboard, or both?

**Comment by zphj1987** [comment]
@GregMeno 
i want disable auth from dashboard  because i have try a grafana over the calamari ,but with the auth  ,something the grafana can not get  

i have  another question  want your help  ,how can i change the limit 256 osd to a big number?

**Comment by GregMeno** [comment]
@zphj1987 I am confused by your question. What limit are you trying to set?
