### ISSUE TITLE
How to : calamari and squid 

### ISSUE THREAD

**Issue by scrat51** [ceph/calamari#383]
I see your repo but I've got a question. So I would like to install calimari in order to manage squid log under Mandriva distribution. As Mandriva Linux has Rpm packets , I suppose to use centos tutorial, don't I ?

And the other things, how to manage it with squid proxy?

Thank you for help

**Comment by GregMeno** [comment]
@scrat51 I am confused. Calamari doesn't manage squid. http://www.squid-cache.org/
It does manage Ceph http://ceph.com/

**Comment by scrat51** [comment]
I mean just the script in perl, not all the framework,isn't it?

Envoyé de mon iPhone

**Comment by scrat51** [comment]
And ceph is for squid log ?

**Comment by dmick** [comment]
Neither Ceph nor Calamari have anything to do with Squid.

Sent from Nine
