### ISSUE TITLE
calamari support   jewel ceph(10.2)?

### ISSUE THREAD

**Issue by zphj1987** [ceph/calamari#441]
@GregMeno
i use calamari 1.3 and ceph 0.94.6 work well.
but i update ceph 0.94.6 to jewel 10.2 ,some problem happen

i konw ceph change some out put from ceph 0.94 to 10.2  like  mdsmap to fsmap

so some thing went wrong,like
 osds = osd_map['osds']
TypeError: 'NoneType' object has no attribute '__getitem__'

so , is there a  plan to  support ceph jewel?  thank you

**Comment by GregMeno** [comment]
@zphj1987 Yes Jewel support for 1.3 is pretty easy, 1.4 has it now. We could backport https://github.com/ceph/calamari/commit/5c331c220190e8e8d513cebdd3325f569ed8e15f What do you think?

**Comment by luhaijiao** [comment]
@GregMeno any estimated time to release calamari 1.4 ?  It's already RC12 :-)

**Comment by laggeduout** [comment]
Can this be closed now 1.4 is release?

**Comment by zphj1987** [comment]
Yes i close it ,thank you for your job
