### ISSUE TITLE
Calamari 1.3 connect Ceph Jewel (Ubuntu 16.04)

### ISSUE THREAD

**Issue by FranBarrera** [ceph/calamari#471]
Hello,

Calamari 1.3 is installed on ubuntu 14.04

I have the error "Ceph servers are connected to Calamari, but no Ceph cluster has been created yet. " But in "/var/log/calamari/cthulhu.log" I can see this: 

<pre>
  File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1019, in _thread_return
    return_data = func(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/ceph.py", line 498, in get_heartbeats
    cluster_heartbeat[fsid] = cluster_status(cluster_handle, fsid_names[fsid])
  File "/var/cache/salt/minion/extmods/modules/ceph.py", line 566, in cluster_status
    mds_epoch = status['mdsmap']['epoch']
KeyError: 'mdsmap'
</pre>
If I do: # salt '*' ceph.get_heartbeats

<pre>
ceph-node:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/salt/minion.py", line 1019, in _thread_return
        return_data = func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/ceph.py", line 498, in get_heartbeats
        cluster_heartbeat[fsid] = cluster_status(cluster_handle, fsid_names[fsid])
      File "/var/cache/salt/minion/extmods/modules/ceph.py", line 566, in cluster_status
        mds_epoch = status['mdsmap']['epoch']
    KeyError: 'mdsmap'
</pre>

Salt is 2014.7.0 (Helium)

**Comment by laggeduout** [comment]
Maybe this (https://github.com/ceph/calamari/commit/5c331c220190e8e8d513cebdd3325f569ed8e15f)

**Comment by kanchana424** [comment]
Failed to connect to Calamari , ceph jewel 10.2.2 ubuntu 14.04

Calamari failing with the below error, detailed information is as follows. 

calamari URL displays below error:

New Calamari Installation
This appears to be the first time you have started Calamari and there are no clusters currently configured.
3 Ceph servers are connected to Calamari, but no Ceph cluster has been created yet. Please use ceph-deploy to create a cluster; please see the Inktank Ceph Enterprise documentation for more details.	
	
When executed ceph-deploy connect again, "calamari.conf"file is changes "master: None". 

ceph version 10.2.2 on ubuntu 14.04
salt version  2014.7.5+ds-1ubuntu1
diamond 3.4.67_all.deb

1. Installed deb packages for calamari on admin/calamari server node

	wget http://download.ceph.com/debian-jewel/pool/main/c/ceph-deploy/ceph-deploy_1.5.34_all.deb
	sudo dpkg -i ceph-deploy_1.5.34_all.deb

2. Downloaded calamari deb packages on admin/calamari server node
	
	sudo wget http://download.ceph.com/calamari/1.3.1/ubuntu/trusty/pool/main/c/calamari/calamari-server_1.3.1.1-1trusty_amd64.deb
	sudo wget http://download.ceph.com/calamari/1.3.1/ubuntu/trusty/pool/main/c/calamari-clients/calamari-clients_1.3.1.1-1trusty_all.deb
	sudo wget http://download.ceph.com/calamari/1.3.1/ubuntu/trusty/pool/main/d/diamond/diamond_3.4.67_all.deb
	
	
3. Installed salt 2014.7 version on admin/calamari server node

	sudo add-apt-repository ppa:saltstack/salt2014-7  
	
4. Then ran the commands below from calamari server  or admin node

	sudo apt-get update
	sudo apt-get install salt-master
	sudo apt-get install salt-minion
	sudo apt-get install -y apache2 libapache2-mod-wsgi libcairo2 supervisor python-cairo libpq5 postgresql
	sudo apt-get -f install
	sudo dpkg -i calamari-server*.deb calamari-clients*.deb
	sudo calamari-ctl initialize

5. Edited ceph.conf file and added 

	[ceph-deploy-calamari]
	master = amcnode

	pushed config file to all other nodes
	ceph-deploy --overwrite-conf config push amcnode siteAosd siteBosd siteCosd
	
6. Installed salt package on other nodes. Copied diamond package to all other nodes and installed

	sudo add-apt-repository ppa:saltstack/salt2014-7  
	sudo dpkg -i diamond_3.4.67_all.deb
    sudo apt-get install  python-support
	
7. Executed the below command from calamari server node /admin node
	
	ceph-deploy calamari connect siteAosd siteBosd siteCosd

8. URL shows all the 3 nodes and requested to "Add". Adding the nodes failed.

9. calamari.conf file in calamari client nodes has "master: None", modified it to "master: amcnode", restarted salt minion.

	sudo vi /etc/salt/minion.d/calamari.conf
			master: amcnode
			
	sudo service salt-minion restart

10. URL still shows the below error:

New Calamari Installation
This appears to be the first time you have started Calamari and there are no clusters currently configured.
3 Ceph servers are connected to Calamari, but no Ceph cluster has been created yet. Please use ceph-deploy to create a cluster; please see the Inktank Ceph Enterprise documentation for more details.	
	
11. **Executed ceph-deploy connect again, now calamari.conf file is changed to "master: None"	again**. 

Thanks for your help in advance.

**Comment by GregMeno** [comment]
@FranBarrera this is a commit that fixes the issue, merged into the 1.3 branch https://github.com/ceph/calamari/commit/f911d6d503e4a1f28f795670be1a3e40e9143f3d

What version are you using?

**Comment by GregMeno** [comment]
@kanchana424 This may be a separate issue. Would you please look in /var/log/calamari/*.log for relevant errors?

**Comment by FranBarrera** [comment]
@GregMeno I was using the package of ubuntu so I'll try with the version that you mention.
I think this can be closed.

Thanks.

**Comment by IamAliBaba** [comment]
Hello,

The same issue was it solved or not ?

Thanks,
-Karen
