### ISSUE TITLE
Must the ceph cluster be created by ceph-deploy way if I want to use calamari?

### ISSUE THREAD

**Issue by Calarence** [ceph/calamari#481]
I have a ceph cluster created by the **MANUAL way** rather than **ceph-deploy**. The UI respond me "3 Ceph servers are connected to Calamari, but no Ceph cluster has been created yet. Please use ceph-deploy to create a cluster; please see the Inktank Ceph Enterprise documentation for more detail".
So I use ceph-deploy  way to create a cluster. As I as excepted, it works.
So my question here is if I want to use calamari, must I create ceph cluster using the ceph-deploy way?

**Comment by Calarence** [comment]
the way to create ceph cluster in order to use calamari

**Comment by GregMeno** [comment]
There is no requirement to use ceph-deploy. 

I am assuming that you're using calamari 1.3something:

The detail that you'll need to know if you're building your own cluster manually can be found here:
https://github.com/ceph/ceph-deploy/blob/master/ceph_deploy/calamari.py

Mostly it's about setting up salt-minion packages on the cluster nodes and then configuring those to point to your calamari instance.

**Comment by Calarence** [comment]
@GregMeno  thanks for your reponse. I have solved this problem. The key is salt version. I use salt-2015-8.1 to replace the last version, ceph cluster are found.

**Comment by GregMeno** [comment]
@Calarence glad to hear it.
