### ISSUE TITLE
update calamari-server-1.3.3-4_g714742d to  calamari-server-1.4.8-0.el7.centos.x86_64  ,visit the home page respones Server Error (500)

### ISSUE THREAD

**Issue by wzyuliyang** [ceph/calamari#485]
when installed the calamari-server-1.3.3 and i visit the homepage

![](http://7xtthx.com1.z0.glb.clouddn.com/16-8-22/98187003.jpg)

after  i upgrade to 1.4.8 

it response 500 error
![](http://7xtthx.com1.z0.glb.clouddn.com/16-8-22/57327907.jpg)

and the log 
 DatabaseError: DatabaseWrapper objects created in a thread can only be used in that same thread. The object with alias 'default' was created in thread id 139745137886976 and this is thread id 139745389392272

ZMQError: Address already in use
2016-08-22 18:03:56,776 - ERROR - calamari Address already in use

so and i found when in install calamari-server-1.4.8 it did not installed httpd,and can not find 80 port from netstat command. is any document to describe the different between 1.3 and 1.4?

**Comment by b-ranto** [comment]
Hi, 1.4 was significantly redesigned for use with different web UI, not calamari-clients and serves mostly as a daemon. Please continue using version 1.3 with calamari-clients at least for now.
